/*
 * File: app/store/Friends.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FriendsWithBeer.store.Friends', {
    extend: 'Ext.data.Store',

    requires: [
        'FriendsWithBeer.model.Friend'
    ],

    config: {
        autoLoad: true,
        autoSync: true,
        model: 'FriendsWithBeer.model.Friend',
        storeId: 'Friends',
        sorters: {
            property: 'lastName'
        },
        grouper: {
            groupFn: function(record) {
                return record.get('lastName')[0];
            }
        }
    }
});