/*
 * File: app/controller/Main.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FriendsWithBeer.controller.Main', {
    extend: 'Ext.app.Controller',

    config: {
        views: [
            'Main',
            'Introduction'
        ],

        refs: {
            btnNoShow: 'intro button#noShow',
            mainTabPanel: 'main'
        },

        control: {
            "btnNoShow": {
                tap: 'onNoShowTap'
            }
        }
    },

    onNoShowTap: function(button, e, options) {
        // persist user preference
        window.localStorage.setItem('FriendsWithBeer_NoShowIntro',true);

        // get pointer to container to destroy
        var objView = button.up('intro');

        // Remove the container from the tabpanel
        this.getMainTabPanel().removeAt(0);

        // Destroy the view after a brief delay
        Ext.Function.defer(function(){
            objView.destroy();
        }, 500);
    }

});